package org.webservice.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ws_scoreSoap", targetNamespace = "http://common.webservice.org/")
public interface WsScoreSoap {

	/**
	 * ��ȡѧ��ѧ��ƽ��ɼ�
	 * 
	 * @param sign
	 * @param time
	 * @param xn
	 * @param xsxh
	 * @param xqM
	 * @return returns org.webservice.common.ArrayOfString
	 */
	@WebMethod(action = "http://common.webservice.org/getStudentAverageScore")
	@WebResult(name = "getStudentAverageScoreResult", targetNamespace = "http://common.webservice.org/")
	@RequestWrapper(localName = "getStudentAverageScore", targetNamespace = "http://common.webservice.org/", className = "org.webservice.common.GetStudentAverageScore")
	@ResponseWrapper(localName = "getStudentAverageScoreResponse", targetNamespace = "http://common.webservice.org/", className = "org.webservice.common.GetStudentAverageScoreResponse")
	public ArrayOfString getStudentAverageScore(
			@WebParam(name = "xn", targetNamespace = "http://common.webservice.org/") String xn,
			@WebParam(name = "xq_m", targetNamespace = "http://common.webservice.org/") String xqM,
			@WebParam(name = "xsxh", targetNamespace = "http://common.webservice.org/") String xsxh,
			@WebParam(name = "time", targetNamespace = "http://common.webservice.org/") String time,
			@WebParam(name = "sign", targetNamespace = "http://common.webservice.org/") String sign);

}
